<a href="https://colab.research.google.com/github/soumitrasamanta506/Machine_Learning/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px

In [ ]:
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [ ]:
df = pd.DataFrame({'feature1':X[:, 0], 'feature2':X[:, 1], 'target':y})

In [ ]:
df.shape

(100, 3)

In [ ]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [ ]:
X_test

array([[ 1.26783024,  0.06601713],
       [ 1.33778919,  0.39121469],
       [-0.71584393,  1.04009073],
       [ 0.58816103, -0.30336264],
       [ 0.41722638,  1.54517675],
       [ 0.11103277, -0.93977911],
       [ 0.63042094,  0.67374365],
       [-0.29974796,  0.39465581],
       [-1.11779526, -1.54664679],
       [ 1.00434481,  0.85107223],
       [-0.14014222,  0.74218626],
       [-0.83690493,  1.64911783],
       [ 0.06385892,  0.50977329],
       [-1.005012  , -2.5690942 ],
       [ 0.5843219 ,  1.56577234],
       [-0.54821131, -0.20180756],
       [-0.5767983 , -0.38011127],
       [ 0.47980156,  0.06833787],
       [ 0.91684508,  1.33357474],
       [-1.26612267,  0.94790724]])

In [ ]:
y_test

array([ 111.40683823,  147.64060871,  -62.40941554,   39.74212202,
        111.94075195,  -13.08989207,  -14.11032368,  -29.44276718,
       -105.6357091 ,  115.85425656,  -13.14169113, -104.32741771,
         24.17045365, -132.27661723,   98.40876657,  -69.0575951 ,
        -74.68702583,  -18.24896802,  131.60655087, -121.81641794])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
y_pred

array([ 104.82690839,  115.79155328,  -40.56974893,   43.5949644 ,
         59.71231884,   -5.51187512,   62.89154409,  -17.23227201,
       -115.22830735,   96.15838661,    1.38035414,  -40.52130541,
         14.1862022 , -122.66087024,   73.62621561,  -47.10733479,
        -52.32510296,   40.82291496,   96.880314  ,  -86.78640154])

In [ ]:
lr.coef_

array([81.26819454, 16.23384652])

In [ ]:
lr.intercept_

np.float64(0.7209216750813621)